name: Build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  NUGET_PROJECT_PATH: nuget/NIX.Analyzers/NIX.Analyzers.csproj
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dotnet
        uses: actions/setup-dotnet@v1

      - name: Restore packages
        run: dotnet restore ${{ env.NUGET_PROJECT_PATH }}

      - name: Build project
        run: dotnet build ${{ env.NUGET_PROJECT_PATH }} --no-restore

      - name: Pack project
        run: dotnet pack ${{ env.NUGET_PROJECT_PATH }} /p:NuspecFile=nuget/NIX.Analyzers/NIX.Analyzers.nuspec --no-restore --no-build --output output

      - name: Save nuget package to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: saved
          path: ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*
